parameters:
  - name: stageName
    type: string
  - name: dependsOn
    type: string
  - name: displayName
    type: string
  - name: variableGroupName
    type: string
  - name: agentPool
    type: string
  - name: artifactName
    type: string
  - name: serviceConnection
    type: string
  - name: subscriptionId
    type: string
  - name: resourceGroupName
    type: string
  - name: location
    type: string
stages:
  - stage: ${{ parameters.stageName }}
    pool: ${{ parameters.agentPool }}
    dependsOn: ${{ parameters.dependsOn }}
    displayName: ${{ parameters.displayName }}
    variables:
      - group: '${{ parameters.variableGroupName }}'
    jobs:
      - deployment: ${{ lower(replace(parameters.displayName,' ', '_')) }}
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: '${{ parameters.artifactName }}'
                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: '${{ parameters.serviceConnection }}'
                    subscriptionId: '${{ parameters.subscriptionId }}'
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: '${{ parameters.resourceGroupName }}'
                    location: '${{ parameters.location }}'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/ARMTemplateForFactory.json'
                    csmParametersFile: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/ARMTemplateParametersForFactory.json'
                    overrideParameters: $(overrideParameters)
                    deploymentMode: 'Incremental'
